#!/usr/bin/env python3
"""Run active synthetic-image detectors and build LR score matrices."""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import re
import sys
import time
from pathlib import Path
from typing import Any

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "src" / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from core.legacy.synthetic_image_detection.pipeline import (  # noqa: E402
    DEFAULT_SYNTHETIC_ANALYSES,
    predict_ensemble,
)

DETECTORS = {
    "ai_image_detector_deploy": "ai-image-detector-deploy",
    "sdxl_flux_detector_v1_1": "sdxl-flux-detector v1.1",
    "bfree": "B-Free",
    "corvi2023": "On the detection of synthetic images generated by diffusion models.",
}


def _detector_id(label: str) -> str | None:
    low = label.lower()
    if "ai-image-detector" in low or "detector-deploy" in low:
        return "ai_image_detector_deploy"
    if "sdxl" in low or "flux-detector" in low:
        return "sdxl_flux_detector_v1_1"
    if "b-free" in low or "bias-free" in low:
        return "bfree"
    if "corvi2023" in low or "dmimagedetection" in low or "synthetic images generated by diffusion" in low:
        return "corvi2023"
    return None


def _float(value: Any) -> float | None:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    if math.isfinite(result):
        return result
    return None


def _raw_score(details: str) -> float | None:
    match = re.search(r"(?:LLR|score)=([-+]?\d+(?:\.\d+)?(?:e[-+]?\d+)?)", details, re.IGNORECASE)
    return _float(match.group(1)) if match else None


def _read_manifest(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    for row in rows:
        row["_manifest"] = str(path)
        row["_root"] = str(path.parent)
    return rows


def _input_path(row: dict[str, str]) -> Path:
    dest = row.get("dest_relative")
    if not dest:
        raise RuntimeError("Manifest row missing dest_relative")
    return Path(row["_root"]) / dest


def _init_output_row(row: dict[str, str], path: Path) -> dict[str, Any]:
    out = {
        "dataset": row.get("dataset", ""),
        "purpose": row.get("purpose", ""),
        "generator": row.get("generator", ""),
        "generator_id": row.get("generator_id", ""),
        "label": row.get("label", ""),
        "y_fake": int(row.get("y_fake", "1" if row.get("label") == "fake" else "0")),
        "source_split": row.get("source_split", ""),
        "source_id": row.get("source_id", ""),
        "dest_relative": row.get("dest_relative", ""),
        "image_path": str(path),
        "image_sha256": row.get("sha256", ""),
        "error": "",
        "elapsed_seconds": "",
    }
    for detector_id in DETECTORS:
        out[f"{detector_id}_fake_prob"] = ""
        out[f"{detector_id}_real_prob"] = ""
        out[f"{detector_id}_raw_score"] = ""
        out[f"{detector_id}_decision"] = ""
        out[f"{detector_id}_device"] = ""
    return out


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys()) if rows else [
        "dataset",
        "purpose",
        "generator",
        "label",
        "y_fake",
        "error",
    ]
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", action="append", required=True, help="Manifest CSV. Can be passed multiple times.")
    parser.add_argument("--out", required=True)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--sample-per-purpose-label", type=int, default=0)
    parser.add_argument("--seed", type=int, default=20260629)
    parser.add_argument("--selected", default=",".join(DEFAULT_SYNTHETIC_ANALYSES))
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()

    selected = [item.strip() for item in args.selected.split(",") if item.strip()]
    rows: list[dict[str, str]] = []
    for manifest in args.manifest:
        rows.extend(_read_manifest(Path(manifest)))
    if args.sample_per_purpose_label > 0:
        grouped: dict[tuple[str, str, str], list[dict[str, str]]] = {}
        for row in rows:
            key = (row.get("dataset", ""), row.get("purpose", ""), row.get("label", ""))
            grouped.setdefault(key, []).append(row)
        rng = random.Random(args.seed)
        sampled: list[dict[str, str]] = []
        for key in sorted(grouped):
            group = grouped[key]
            rng.shuffle(group)
            sampled.extend(group[: args.sample_per_purpose_label])
        rows = sampled
    if args.limit > 0:
        rows = rows[: args.limit]

    out_path = Path(args.out)
    existing: list[dict[str, Any]] = []
    done_paths = set()
    if args.resume and out_path.exists():
        with out_path.open(encoding="utf-8") as fh:
            existing = list(csv.DictReader(fh))
        done_paths = {row.get("image_path", "") for row in existing if row.get("image_path")}

    output_rows = existing[:]
    for idx, row in enumerate(rows, start=1):
        path = _input_path(row)
        if str(path) in done_paths:
            continue
        out_row = _init_output_row(row, path)
        start = time.time()
        try:
            with Image.open(path) as image:
                result_rows = predict_ensemble(image.copy(), selected_analyses=selected)
            for result in result_rows:
                if len(result) < 6:
                    continue
                detector = _detector_id(result[0])
                if detector is None:
                    continue
                out_row[f"{detector}_fake_prob"] = result[1]
                out_row[f"{detector}_real_prob"] = result[2]
                out_row[f"{detector}_raw_score"] = _raw_score(result[3])
                out_row[f"{detector}_decision"] = result[4]
                out_row[f"{detector}_device"] = result[5]
        except Exception as exc:
            out_row["error"] = repr(exc)
        out_row["elapsed_seconds"] = f"{time.time() - start:.3f}"
        output_rows.append(out_row)
        if idx % 10 == 0:
            _write_csv(out_path, output_rows)
            print(f"Processed {idx}/{len(rows)}", flush=True)

    _write_csv(out_path, output_rows)
    summary = {
        "out": str(out_path),
        "rows": len(output_rows),
        "errors": sum(1 for row in output_rows if row.get("error")),
        "detectors": DETECTORS,
        "selected": selected,
    }
    out_path.with_suffix(".summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    os.environ.setdefault("PYTHONHASHSEED", "0")
    main()
