"""Official GRIP CLIP-D inference wrapper.

This follows ``grip-unina/ClipBased-SyntheticImageDetection`` instead of the
TrueBees single-image wrapper: CLIP normalization, bicubic Clip224 preprocessing,
``clipdet_latent10k_plus`` weights, and LLR>0 decision.
"""

from __future__ import annotations

import logging
import math
import sys
from contextlib import contextmanager, suppress
from typing import Callable

import torch
from PIL import Image
from torchvision.transforms import CenterCrop, Compose, InterpolationMode, Normalize, Resize, ToTensor

from core.gpu_inference import device_display_label, release_gpu_memory, resolve_inference_device, run_with_device_fallback
from core.legacy.truebees_clip_d.clipd_runtime import (
    clipd_config_path,
    clipd_runtime_status,
    clipd_vendor_dir,
    clipd_weights_dir,
)

logger = logging.getLogger(__name__)

ProgressFn = Callable[[int, str], None] | None
MODEL_LABEL = "GRIP CLIP-D (clipdet_latent10k_plus)"
MODEL_NAME = "clipdet_latent10k_plus"
CORVI2023_MODEL_NAME = "Corvi2023"
CORVI2023_MODEL_LABEL = "On the detection of synthetic images generated by diffusion models. (Corvi2023)"
CORVI2023_REPO = "github.com/grip-unina/DMimageDetection"
CORVI2023_TILE_SIZE = 1024

_cache: dict[str, tuple[torch.nn.Module, Compose]] = {}


@contextmanager
def _clipd_vendor_context():
    vendor = str(clipd_vendor_dir())
    inserted = vendor not in sys.path
    if inserted:
        sys.path.insert(0, vendor)
    try:
        yield
    finally:
        if inserted:
            with suppress(ValueError):
                sys.path.remove(vendor)


def _clear_vendor_imports() -> None:
    for key in list(sys.modules):
        if key in {"networks", "utils"} or key.startswith(("networks.", "utils.")):
            sys.modules.pop(key, None)


def clear_clipd_model_cache() -> None:
    release_gpu_memory(*(model for model, _transform in _cache.values()))
    _cache.clear()
    release_gpu_memory()


def _sigmoid_from_llr(llr: float) -> float:
    if llr >= 0:
        z = math.exp(-llr)
        return 1.0 / (1.0 + z)
    z = math.exp(llr)
    return z / (1.0 + z)


def _load_model(device: torch.device, model_name: str = MODEL_NAME) -> tuple[torch.nn.Module, Compose]:
    key = f"{model_name}:{device.type}"
    if key in _cache:
        return _cache[key]
    _clear_vendor_imports()
    with _clipd_vendor_context():
        import yaml
        from networks import create_architecture, load_weights

        with open(clipd_config_path(model_name), encoding="utf-8") as fh:
            config = yaml.load(fh, Loader=yaml.FullLoader)
        patch_size = config["patch_size"]
        norm_type = config["norm_type"]
        if model_name == MODEL_NAME and (patch_size != "Clip224" or norm_type != "clip"):
            raise RuntimeError(f"Config CLIP-D inesperada: {config}")

        model = create_architecture(config["arch"])
        model = load_weights(model, str(clipd_weights_dir() / model_name / config["weights_file"]))
        model = model.to(device).eval()
        transform_steps = []
        if patch_size == "Clip224":
            transform_steps.extend(
                [
                    Resize(224, interpolation=InterpolationMode.BICUBIC),
                    CenterCrop((224, 224)),
                ]
            )
        elif isinstance(patch_size, int) and patch_size > 0:
            transform_steps.append(CenterCrop(patch_size))

        transform_steps.append(ToTensor())
        if norm_type == "clip":
            transform_steps.append(
                Normalize(
                    mean=(0.48145466, 0.4578275, 0.40821073),
                    std=(0.26862954, 0.26130258, 0.27577711),
                )
            )
        elif norm_type == "resnet":
            transform_steps.append(
                Normalize(
                    mean=(0.485, 0.456, 0.406),
                    std=(0.229, 0.224, 0.225),
                )
            )
        elif norm_type != "none":
            raise RuntimeError(f"Normalizacao CLIP-D inesperada: {norm_type}")
        transform = Compose(transform_steps)

    _cache[key] = (model, transform)
    return model, transform


def _output_to_llr(output) -> float:
    if output.ndim == 2 and output.shape[1] == 1:
        return float(output[0, 0])
    if output.ndim == 2 and output.shape[1] == 2:
        return float(output[0, 1] - output[0, 0])
    return float(output.reshape(-1)[0])


def _extract_tiles(image: Image.Image, tile_size: int) -> list[Image.Image]:
    width, height = image.size
    if width <= tile_size and height <= tile_size:
        return [image]
    tiles = []
    for y in range(0, height, tile_size):
        for x in range(0, width, tile_size):
            box = (x, y, min(x + tile_size, width), min(y + tile_size, height))
            tiles.append(image.crop(box))
    return tiles


def infer_clipd_from_pil(image: Image.Image, device: torch.device, model_name: str = MODEL_NAME) -> float:
    model, transform = _load_model(device, model_name)
    tensor = transform(image.convert("RGB")).unsqueeze(0).to(device)
    with torch.no_grad():
        output = model(tensor).detach().cpu().numpy()
    return _output_to_llr(output)


def infer_corvi2023_from_pil(
    image: Image.Image,
    device: torch.device,
    tile_size: int = CORVI2023_TILE_SIZE,
) -> tuple[float, int, bool]:
    model, transform = _load_model(device, CORVI2023_MODEL_NAME)
    rgb = image.convert("RGB")
    tiles = _extract_tiles(rgb, tile_size)
    logits: list[float] = []
    for tile in tiles:
        tensor = transform(tile).unsqueeze(0).to(device)
        with torch.no_grad():
            output = model(tensor).detach().cpu().numpy()
        logits.append(_output_to_llr(output))
    llr = float(sum(logits) / len(logits)) if logits else 0.0
    return llr, len(tiles), len(tiles) > 1


def predict_clipd_row(image: Image.Image, on_progress: ProgressFn = None) -> list[str] | None:
    ok, reason = clipd_runtime_status()
    if not ok:
        logger.debug("GRIP CLIP-D indisponivel: %s", reason)
        return None

    preferred = resolve_inference_device()
    if on_progress:
        on_progress(66, f"Inferindo {MODEL_LABEL} em {device_display_label(preferred)}...")

    def _run(dev: torch.device):
        return infer_clipd_from_pil(image, dev)

    try:
        llr, device = run_with_device_fallback(
            _run,
            on_fallback=clear_clipd_model_cache,
            on_before_cpu_fallback=lambda _reason: on_progress and on_progress(66, f"{MODEL_LABEL} em CPU - fallback VRAM..."),
        )
    except Exception as exc:
        logger.warning("GRIP CLIP-D falhou: %s", exc)
        return None

    prob = _sigmoid_from_llr(llr)
    real_score = 1.0 - prob
    decision = "AI" if llr > 0 else "REAL"
    return [
        MODEL_LABEL,
        f"{prob:.4f}",
        f"{real_score:.4f}",
        f"LLR={llr:.4f}",
        decision,
        device_display_label(device.type),
    ]


def predict_corvi2023_row(image: Image.Image, on_progress: ProgressFn = None) -> list[str] | None:
    ok, reason = clipd_runtime_status(CORVI2023_MODEL_NAME)
    if not ok:
        logger.debug("Corvi2023 indisponivel: %s", reason)
        return None

    preferred = resolve_inference_device()
    if on_progress:
        on_progress(
            54,
            f"Inferindo {CORVI2023_MODEL_LABEL} em tiles {CORVI2023_TILE_SIZE}px ({device_display_label(preferred)})...",
        )

    def _run(dev: torch.device):
        return infer_corvi2023_from_pil(image, dev, CORVI2023_TILE_SIZE)

    try:
        (llr, num_tiles, tiled), device = run_with_device_fallback(
            _run,
            on_fallback=clear_clipd_model_cache,
            on_before_cpu_fallback=lambda _reason: on_progress
            and on_progress(54, f"{CORVI2023_MODEL_LABEL} em CPU - fallback VRAM..."),
        )
    except Exception as exc:
        logger.warning("Corvi2023 falhou: %s", exc)
        return None

    prob = _sigmoid_from_llr(llr)
    real_score = 1.0 - prob
    decision = "AI" if llr > 0 else "REAL"
    tile_note = f"LLR={llr:.4f}; tiles={num_tiles}x{CORVI2023_TILE_SIZE}px" if tiled else f"LLR={llr:.4f}"
    return [
        CORVI2023_MODEL_LABEL,
        f"{prob:.4f}",
        f"{real_score:.4f}",
        f"{tile_note}; repo={CORVI2023_REPO}",
        decision,
        device_display_label(device.type),
    ]

